'use client';

import React from 'react';
import { PredictiveStep } from '@/types';
import { 
  AreaChart, 
  Area, 
  XAxis, 
  YAxis, 
  Tooltip, 
  ResponsiveContainer, 
  CartesianGrid 
} from 'recharts';
import { TrendingUp, Clock, AlertCircle } from 'lucide-react';

interface PredictiveRiskChartProps {
  forecast: PredictiveStep[];
  hazardType: string;
}

export default function PredictiveRiskChart({ forecast, hazardType }: PredictiveRiskChartProps) {
  const chartData = forecast.map(f => ({
    time: f.label,
    value: f.value,
    risk: f.riskScore,
    population: f.predictedPopulationImpact
  }));

  const unitLabel = forecast[0]?.unit || 'm';

  return (
    <div className="glass-panel rounded-2xl border border-cyan-500/20 p-4 bg-navy-950/80 shadow-xl flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between pb-2 border-b border-slate-800">
        <div className="flex items-center space-x-2">
          <TrendingUp className="w-4 h-4 text-cyan-400" />
          <h4 className="font-heading font-bold text-xs uppercase tracking-wider text-slate-200">
            PREDICTIVE HAZARD EVOLUTION (+70 MIN)
          </h4>
        </div>
        <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-950 border border-cyan-800 text-cyan-300">
          AI DIFFUSION MODEL
        </span>
      </div>

      {/* Chart container */}
      <div className="h-44 w-full pt-3">
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={chartData} margin={{ top: 5, right: 10, left: -20, bottom: 0 }}>
            <defs>
              <linearGradient id="riskGradient" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor="#00F0FF" stopOpacity={0.4}/>
                <stop offset="95%" stopColor="#00F0FF" stopOpacity={0.0}/>
              </linearGradient>
            </defs>
            <CartesianGrid strokeDasharray="3 3" stroke="#1E293B" vertical={false} />
            <XAxis 
              dataKey="time" 
              stroke="#64748B" 
              fontSize={10} 
              tickLine={false} 
            />
            <YAxis 
              stroke="#64748B" 
              fontSize={10} 
              tickLine={false}
              domain={['auto', 'auto']}
            />
            <Tooltip 
              contentStyle={{ 
                backgroundColor: '#0B1226', 
                borderColor: '#00F0FF', 
                borderRadius: '8px', 
                fontSize: '11px',
                color: '#fff' 
              }} 
            />
            <Area 
              type="monotone" 
              dataKey="value" 
              name={`Level (${unitLabel})`} 
              stroke="#00F0FF" 
              strokeWidth={2}
              fillOpacity={1} 
              fill="url(#riskGradient)" 
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      {/* Prediction Cards Ribbon */}
      <div className="grid grid-cols-4 gap-2 pt-3 border-t border-slate-800 text-center font-mono">
        {forecast.map((step, idx) => (
          <div key={idx} className="p-2 rounded-xl bg-navy-900/60 border border-slate-800/80">
            <span className="text-[10px] text-slate-400 block">{step.label}</span>
            <span className="font-bold text-xs text-cyan-300">
              {step.value} {step.unit}
            </span>
            <span className="text-[9px] text-red-400 block mt-0.5">
              Risk: {step.riskScore}
            </span>
          </div>
        ))}
      </div>

      {/* Model Disclaimer */}
      <div className="mt-2 text-[10px] font-mono text-slate-500 flex items-center gap-1">
        <AlertCircle className="w-3 h-3 text-slate-500 flex-shrink-0" />
        <span>Simulated/demo predictions are generated by AI fluid dynamics. Not official forecasts.</span>
      </div>
    </div>
  );
}
